name: weather

services:
  app:
    container_name: app
    image: donovanbroquin/iut:latest
    ports:
      - 8222:8080
      - 5173:5173
    volumes:
      - ../weather:/app
    restart: unless-stopped
    networks:
      - weather

  valkey:
    container_name: valkey
    image: valkey/valkey:8.1.3-alpine3.22
    restart: unless-stopped
    networks:
      - weather

  mailpit:
    container_name: mailpit
    image: axllent/mailpit:v1.27.7
    ports:
      - 8225:8025 
    restart: unless-stopped
    networks:
      - weather

networks:
  weather:
    driver: bridge
