<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WeatherController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\ProfileController;

// HOME REDIRECT
// so they dont see a blank page
Route::get('/', function () {
    return redirect()->route('dashboard');
});

// Dashboard
// i use middleware only logged users can see it
Route::get('/dashboard', [WeatherController::class, 'index'])
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

// 3. CITY ACTIONS
// grouping these routes because they all need the user to be logged in
Route::middleware(['auth', 'verified'])->group(function () {

    // the search form when the user types a city name
    Route::post('/city/search', [CityController::class, 'search'])->name('city.search');

    // dynamic route /city/paris or /city/london
    // it shows the detailed forecast for that specific place
    Route::get('/city/{city}', [CityController::class, 'show'])->name('city.show');

    // action to save a city as the "main" one on the dashboard
    // using post because we are changing the session data
    Route::post('/city/set-main', [CityController::class, 'setMain'])->name('city.setMain');

    // action to add or remove a city from the favorites list
    Route::post('/city/toggle-favorite', [CityController::class, 'toggleFavorite'])->name('city.toggleFavorite');
});

// standard profile routes generated by laravel breeze
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';
